"""
Django settings for content_engine project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# The accessor used below (env('KEY'), env.bool('KEY'), env.db(), ...) to read
# config from the environment instead of hardcoding it in this file.
env = environ.Env()
# Loads BASE_DIR/.env into the real process environment (os.environ) if that
# file exists - true only in local dev, since .env is gitignored and never
# deployed. In production there's no .env file; Azure sets the same variable
# names directly as environment variables, so every env(...) call below reads
# from the same place (os.environ) either way - this line just seeds it
# locally before anything else runs.
env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No default - a missing SECRET_KEY should crash startup loudly, not fall
# back to an insecure value the way the old hardcoded string did.
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (not True) so a missing env var fails safe into
# production mode instead of accidentally exposing debug info.
DEBUG = env.bool('DEBUG', default=False)

# The hostnames this Django instance will answer for. Defaults to an empty
# list (Django's own default) rather than a permissive one - an empty prod
# value should reject every request with a 400, not silently allow any Host
# header through.
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'content',
    'api',
    'corsheaders',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Dev-only in the single-origin production layout (Decision 108) - nginx and
# gunicorn share one origin there, so no cross-origin request exists to
# allow. This only matters for the dev setup, where the Vite server and
# Django run on different ports.
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])

# Required whenever the frontend sends fetch(..., { credentials: 'include' }).
# Cannot be combined with CORS_ALLOW_ALL_ORIGINS=True - the CORS spec
# forbids "any origin" + "send credentials" together, since that would
# defeat the point of scoping cookies to trusted origins.
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'content_engine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'content_engine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# env.db() parses a single DATABASE_URL string
# (postgres://user:pass@host:port/name) into this dict's ENGINE/NAME/USER/
# PASSWORD/HOST/PORT shape, inferring the postgresql backend from the
# "postgres://" scheme. Matches the single connection-string format managed
# Postgres providers (including Azure's) hand you.
DATABASES = {
    'default': env.db('DATABASE_URL'),
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DEFAULT_AUTHENTICATION_CLASSES tells DRF how to turn an incoming request
# into request.user. JWTAuthentication reads "Authorization: Bearer <token>",
# checks the signature against SECRET_KEY, and if it's valid + not expired,
# loads the User named in the token's payload - no database lookup for the
# token itself (Decision 79/81).
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.auth.authentication.CookieJWTAuthentication',
    ],
}

# Token lifetimes. Short-lived access token limits how long a leaked token
# stays useful, since V1 has no server-side revoke (Decision 80). The
# refresh token is what the client trades in for a new access token once
# it expires, via POST /api/auth/refresh/.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}
